web_server:
    build: .
    ports:
        - 5000:5000
    command: npm run start
    links:
        - mongo

mongo:
    image: mongo:latest
    container_name: mongo
    command: mongod --smallfiles
    expose:
        - 27017
